
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 11 23:14:21 EDT 2016
//----------------------------------------------------

package ic.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CBRACE = 19;
  public static final int FUNCTION = 44;
  public static final int MULT = 31;
  public static final int GE = 41;
  public static final int UNIT = 45;
  public static final int SEMI = 23;
  public static final int CONTINUE = 16;
  public static final int INT = 11;
  public static final int LIBRARY = 33;
  public static final int MINUS = 30;
  public static final int OBRACE = 18;
  public static final int CLS_ID = 47;
  public static final int OBRACKET = 24;
  public static final int NOT = 37;
  public static final int AND = 35;
  public static final int LT = 38;
  public static final int CBRACKET = 25;
  public static final int OR = 36;
  public static final int COMMA = 22;
  public static final int CLASS = 2;
  public static final int DIV = 32;
  public static final int PLUS = 29;
  public static final int IF = 5;
  public static final int THIS = 4;
  public static final int ID = 46;
  public static final int DOT = 28;
  public static final int LE = 39;
  public static final int EOF = 0;
  public static final int BOOLEAN = 13;
  public static final int RETURN = 3;
  public static final int CPAREN = 21;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int EQEQ = 42;
  public static final int NULL = 17;
  public static final int MOD = 34;
  public static final int BREAK = 14;
  public static final int VOID = 8;
  public static final int EQ = 26;
  public static final int COLON = 27;
  public static final int ELSE = 9;
  public static final int OPAREN = 20;
  public static final int WHILE = 12;
  public static final int NE = 43;
  public static final int EXTENDS = 6;
  public static final int BOOL_LIT = 50;
  public static final int STRING = 15;
  public static final int STRING_LIT = 49;
  public static final int INT_LIT = 48;
  public static final int GT = 40;
  public static final int LENGTH = 10;
}

